#!/usr/bin/env python3
# test generated by chatgpt 5.6 sol :)

import socket
import struct
import sys

HOST = "127.0.0.1"
PORT = 7000

SEND_MESSAGE = 0x11

if len(sys.argv) < 2:
    print(f"usage: {sys.argv[0]} <message>")
    sys.exit(1)

payload = sys.argv[1].encode("utf-8")

version = 1
packet_id = 1

# uint8 type
# uint8 version
# uint32 id
# uint32 payloadLen
header = struct.pack(
    "!BBII",
    SEND_MESSAGE,
    version,
    packet_id,
    len(payload)
)

packet = header + payload

with socket.create_connection((HOST, PORT)) as sock:
    sock.sendall(packet)

print(
    f"sent SEND_MESSAGE "
    f"type=0x{SEND_MESSAGE:02x} "
    f"id={packet_id} "
    f"payloadLen={len(payload)}"
)
